sudo: required

language: cpp
compiler:
- gcc
- clang

before_install:
- git checkout $TRAVIS_BRANCH

- if [ $(bii-support/travis/git/is_last_commit_travis.sh) = "true" ] ; then exit 0 ; fi
- bii-support/travis/git/configure.sh

install:
- bii-support/travis/install/all-desktop.sh

- export TRAVIS_CXX=$CXX

script:
- bii-support/linux/build/default.sh
- Xvfb :1 -screen 0 640x480x16 & X_DISPLAY_PID=$(echo $!)
- DISPLAY=:1 valgrind --leak-check=full --gen-suppressions=all --suppressions=suppress.vg --show-reachable=yes --error-exitcode=1 "bin/${BII_USER}_${BLOCK_NAME}_test_main"
- kill -s SIGINT $X_DISPLAY_PID

after_success:
- bii-support/travis/publish/biicode.sh

env:
  global:
  - USER_EMAIL=azriel91@gmail.com
  - USER_NAME="azriel"
  - COMMIT_IGNORE_BUILD="Promoted version. ***travis***"
  - BLOCK_NAME=sl_desktop_demo_wx
  - BII_USER=azriel
  # BII_PASSWORD
  - secure: "dekhJJnZp5Y6d5kjBuw9VzH9ouCkhuUqw2xe9yomU2mvp2c/9od13GZIu6zEqZnh7RSFuk1pvujwG0XMA8zYNxCv9pxbFmM+4VSd12lu5Uruiql2Z0tSmU3rX1tNje/LrHAt3z1uBkYuZrhOFs46uW4J5mbi75zmo+VisAaYdlo="
  # GITHUB_TOKEN
  - secure: "I+qTUP4wP1dcy5zkhIsjuea3vwMLm/+BDUQqzC+3GyZNrlqXybxUFQ3Wce15V/tP+/gU6zujy+DFAo0+y3zb1bZhvKWGQMXpvSEI0JSccYmUsHNC/VaESc2QBaB7SkHlkKocBcPNCJCe48v/aeauxP0/IQeNc/XwpWP17LFhd7k="
  matrix:
  - BUILD_SHARED_LIBS=OFF
  - BUILD_SHARED_LIBS=ON